## Reshaping the array


In [4]:
import numpy as np

In [5]:
x=np.arange(1,13)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
x1=x.reshape(2,6)
x1,x

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [9]:
x2=np.arange(2,16).reshape(7,2)
x2

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [11]:
x3=np.linspace(10,20,16).reshape(2,8)
x3

array([[10.        , 10.66666667, 11.33333333, 12.        , 12.66666667,
        13.33333333, 14.        , 14.66666667],
       [15.33333333, 16.        , 16.66666667, 17.33333333, 18.        ,
        18.66666667, 19.33333333, 20.        ]])

In [14]:
y=np.array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
y, y.shape

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 (2, 6))

In [20]:
y1=y.reshape(2,2,3)
y1, y1.shape,y1.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 (2, 2, 3),
 3)

In [24]:
#zeros
zero_array = np.zeros((3,4), dtype='int32')
zero_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
#zwero_like
z=np.zeros_like(y)
z

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [29]:
o_a = np.ones((5,3), dtype='int32')
o_a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [28]:
o = np.ones_like(y)
o

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])