In [2]:
import numpy as np



## this module gives functionalities to work with numerical calculation (numpy.org)

In [2]:
x=np.array([28,20,26,42,48,46])
x,type(x)

(array([28, 20, 26, 42, 48, 46]), numpy.ndarray)

In [8]:
maths=np.array([86,94,98,99,92])
physics=np.array([89,91,86,83,95])
print('maths marks: ', maths)
type(maths), physics

maths marks:  [86 94 98 99 92]


(numpy.ndarray, array([89, 91, 86, 83, 95]))

In [6]:
total=maths + physics
total

array([175, 185, 184, 182, 187])

In [9]:
maths**2

array([7396, 8836, 9604, 9801, 8464])

In [10]:
np.log2(maths),np.log10(maths)

(array([6.42626475, 6.55458885, 6.61470984, 6.62935662, 6.52356196]),
 array([1.93449845, 1.97312785, 1.99122608, 1.99563519, 1.96378783]))

In [11]:
angles =np.array([0,30,45,60,90])

In [12]:
np.sin(np.radians(angles)), np.cos(np.radians(angles))

(array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ]),
 array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
        6.12323400e-17]))

In [14]:
import numpy as np

In [21]:
marks = np.array([89,91,98,94,83,99])
s = marks.shape
r = marks.reshape(2,3)
m = np.mean(marks)
marks,s,r,m

(array([89, 91, 98, 94, 83, 99]),
 (6,),
 array([[89, 91, 98],
        [94, 83, 99]]),
 92.33333333333333)

In [24]:
maths=np.array([86,94,98,99,92]) #1d-array is a collection of elements
maths/100

array([0.86, 0.94, 0.98, 0.99, 0.92])

In [29]:
maths=np.array([86,94,98,99,92])
physics=np.array([89,91,86,83,95])
chemistry=np.array([94,96,89,91,93])
marks = np.array([[86,94,98,99,92],
                 [89,91,86,83,95],
                 [94,96,89,91,93]]) #2d-array is a set of 1d-array
marks, marks.shape, marks.ndim

(array([[86, 94, 98, 99, 92],
        [89, 91, 86, 83, 95],
        [94, 96, 89, 91, 93]]),
 (3, 5),
 2)

In [30]:
#create a (5,3) array
x=np.array([[1,2,3],[4,5,6],[7,8,9],[1,1,1],[9,8,7]])
x,x.shape,x.ndim #attribute

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 1, 1],
        [9, 8, 7]]),
 (5, 3),
 2)

In [39]:
m3=np.array([[1,2,3],[4,5,6]])

m4=np.array([[3,2,1],[6,5,4]])

m3+m4,m3-m4,m3*m4,m3/m4, m3**m4, m4**m3

(array([[ 4,  4,  4],
        [10, 10, 10]]),
 array([[-2,  0,  2],
        [-2,  0,  2]]),
 array([[ 3,  4,  3],
        [24, 25, 24]]),
 array([[0.33333333, 1.        , 3.        ],
        [0.66666667, 1.        , 1.5       ]]),
 array([[   1,    4,    3],
        [4096, 3125, 1296]]),
 array([[   3,    4,    1],
        [1296, 3125, 4096]]))

In [40]:
m2=np.array([[2,3],[4,5],[6,7]])
d=m3.dot(m2) #method
d

array([[28, 34],
       [64, 79]])

In [41]:
d1=m2.dot(m3)
d1

array([[14, 19, 24],
       [24, 33, 42],
       [34, 47, 60]])

In [42]:
m3

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
m3.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
#generating a seq of no.
#np.arange(start, stop, step)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x1=np.arange(1,50,2)
x1.shape,x1.ndim,type(x1), x1

((25,),
 1,
 numpy.ndarray,
 array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45, 47, 49]))

In [6]:
np.linspace(1,10, 19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [7]:
(10-1)/(19-1) #[(stop-start)/(n-1)]

0.5

In [8]:
np.linspace(1,20,77) #in linspace the end point includes

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,
        3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,  5.25,
        5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,  7.5 ,
        7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
       10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75, 12.  ,
       12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  , 14.25,
       14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25, 16.5 ,
       16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 , 18.75,
       19.  , 19.25, 19.5 , 19.75, 20.  ])

In [10]:
np.linspace(1,10,20,endpoint=False) #by defualt the endpoint is True, [(stop-start)/n]

array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55])

In [11]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])