## Random Numbers

In [1]:
import numpy as np

In [6]:
np.random.random_sample(9)

array([0.84110833, 0.02234378, 0.03862892, 0.4220899 , 0.55843372,
       0.29830858, 0.09220828, 0.71928953, 0.03438944])

In [17]:
np.random.random_sample((3,2))

array([[0.04338245, 0.80151684],
       [0.00326234, 0.65812796],
       [0.77120744, 0.00989991]])

In [11]:
#98 will not include
marks = np.random.randint(76,98,(3,5))
marks

array([[96, 81, 79, 90, 79],
       [95, 85, 87, 94, 93],
       [96, 86, 86, 80, 76]])

In [14]:
m1=np.random.randint(1,15,(3,5))
m1

array([[ 6,  6,  4,  4,  2],
       [ 6, 10,  6, 11, 10],
       [ 5,  7, 12, 14, 14]])

In [15]:
m2=np.random.randint(10,20,(5,4))
m2

array([[17, 16, 12, 11],
       [14, 13, 10, 14],
       [16, 18, 17, 12],
       [16, 18, 11, 11],
       [17, 14, 14, 13]])

In [16]:
m1.dot(m2)

array([[348, 346, 272, 268],
       [684, 672, 535, 529],
       [837, 835, 684, 633]])

In [28]:
5*np.random.random_sample((3,4))+5

array([[5.86522401, 6.40312137, 5.12472778, 5.97686747],
       [8.19478045, 8.67493764, 8.23675644, 6.40034287],
       [7.13375985, 7.75681941, 8.36487944, 6.7556328 ]])

In [34]:
np.random.seed(10)
np.random.randint(10,20,10)
# to get the same number always we use seed

array([19, 14, 10, 11, 19, 10, 11, 18, 19, 10])

In [36]:
np.random.seed(0)
np.random.randint(10,20,10)

array([15, 10, 13, 13, 17, 19, 13, 15, 12, 14])

In [37]:
x=np.random.randint(1,50,(2,5))
x

array([[24,  7, 25, 25, 13],
       [ 2, 39, 40, 24, 47]])

In [42]:
np.arange(1,41).reshape(2,5,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]],

       [[21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]]])

In [44]:
marks=np.random.randint(1,10,(2,6))
marks

array([[9, 2, 4, 4, 4, 8],
       [1, 2, 1, 5, 8, 4]])

In [46]:
marks[:2], marks[:2,:3]

(array([[9, 2, 4, 4, 4, 8],
        [1, 2, 1, 5, 8, 4]]),
 array([[9, 2, 4],
        [1, 2, 1]]))

In [47]:
marks[:2,-3:]

array([[4, 4, 8],
       [5, 8, 4]])

In [48]:
marks=np.random.randint(78,100,(2,3,6))
marks

array([[[89, 96, 80, 78, 78, 82],
        [99, 83, 84, 86, 98, 95],
        [93, 82, 87, 88, 79, 79]],

       [[85, 87, 81, 84, 89, 92],
        [96, 78, 92, 81, 99, 90],
        [88, 98, 89, 82, 84, 82]]])

In [49]:
marks[0,:2,:3] #marks of 1st test 2 subjects of 1st 3 sudents


array([[89, 96, 80],
       [99, 83, 84]])